car_rent/car_rent/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('api/v1.0/cars/',include('main.api.urls',namespace='api_cars')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rent/main/api/urls.py
from django.urls import path
from main.api.views import ModelListView,CarListView,AllCarsListView,OrderCreateView, \
CarClassesView,CarMarkaView

app_name = 'api_cars'

urlpatterns = [
    path('cars/',CarListView.as_view(),name='cars'),
    path('models/',ModelListView.as_view(),name= 'models'),
    path('all/',AllCarsListView.as_view(),name='all'),
    path('orders/',OrderCreateView.as_view(),name='orders'),
    path('classes/',CarClassesView.as_view(),name='classes'),
    path('markas/',CarMarkaView.as_view(),name='markas')

]

car_rent/main/urls.py
from django.urls import path
from main.views import MainPageView,CarDetailView,CreateOrderView,OrderSuccessView,AboutUsView,ContactPageView


app_name = 'main'


urlpatterns = [
    path('',MainPageView.as_view(),name='home'),
    path('car-detail/<int:pk>/',CarDetailView.as_view(),name='car-detail'),
    path('create-order/',CreateOrderView.as_view(),name='create-order'),
    path('success/',OrderSuccessView.as_view(),name='success'),
    path('about/',AboutUsView.as_view(),name='about-us'),
    path('contacts/',ContactPageView.as_view(),name='contacts')

]

car_rent/main/models.py
from django.db import models



class CarMarka(models.Model):
    marka = models.CharField(max_length=50, verbose_name='Marka')

    def __str__(self):
        return self.marka

class CarModel(models.Model):
    marka = models.ForeignKey(CarMarka, on_delete=models.CASCADE, verbose_name='Marka',related_name='models')
    model = models.CharField(max_length=50, verbose_name='Model')

    def __str__(self):
        return self.model

class CarYear(models.Model):
    # model = models.ForeignKey(CarModel, on_delete=models.CASCADE, verbose_name='Model',related_name='years')
    year = models.PositiveIntegerField(verbose_name='Год выпуска')

    def __str__(self):
        return str(self.year)

class Transmission(models.Model):
    name = models.CharField(max_length=50, verbose_name='Коробка')

    def __str__(self):
        return str(self.name)

class Fuel(models.Model):
    name = models.CharField(max_length=50, verbose_name='Топливо')

    def __str__(self):
        return str(self.name)

class Type(models.Model):
    name = models.CharField(max_length=50, verbose_name='Кузов')

    def __str__(self):
        return str(self.name)

class CarClass(models.Model):
    name = models.CharField(max_length=50, verbose_name='Класс')

    def __str__(self):
        return str(self.name)

# Create your models here.
class Car(models.Model):
    marka = models.ForeignKey(CarMarka, on_delete=models.CASCADE, null=True, verbose_name='Марка',related_name='cars')
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE, null=True, verbose_name='Модель',related_name='cars')
    car_year = models.ForeignKey(CarYear, on_delete=models.CASCADE, null=True, verbose_name='Год выпуска',related_name='cars')
    transmission = models.ForeignKey(Transmission,on_delete=models.CASCADE, null=True, verbose_name='Коробка передач',related_name='cars')
    main_image = models.ImageField('Main image', upload_to='images/main')
    price = models.PositiveIntegerField(verbose_name='Стоимость')
    fuel = models.ForeignKey(Fuel, on_delete=models.CASCADE, null=True, verbose_name='Топливо', related_name='cars')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, null=True, verbose_name='Кузов', related_name='cars')
    car_class = models.ForeignKey(CarClass, on_delete=models.CASCADE, null=True, verbose_name='Класс авто', related_name='cars')
    seats = models.CharField(max_length=50, verbose_name='Количество сиденье')
    comment = models.TextField('Oписание')

    is_published = models.BooleanField(default=False, verbose_name='Опубликован')
    taxi = models.BooleanField(default=False, verbose_name='Такси')

    def get_image(self):
        return self.main_image.url

    def get_car(self):
        return f'{self.marka.marka} {self.model.model} {self.car_year.year}'




class Images(models.Model):
    carr = models.ForeignKey(Car,on_delete=models.CASCADE, verbose_name='Car',related_name='images')
    images = models.ImageField('Допольнительные фотографии', upload_to='images/allImg')

    def __str__(self):
        return f'{self.images}'


class OrderData(models.Model):
    name=models.CharField(max_length=50, verbose_name='Имя')
    surname=models.CharField(max_length=50, verbose_name='Фамилия и Отчество')
    phone_number=models.CharField(max_length=50, verbose_name='Номер телефона')
    order_data=models.CharField(max_length=250, verbose_name='Заказ')
    passport_first = models.ImageField('Пасспорт 1', upload_to='images/users',default='',blank=True,null=True)
    passport_second = models.ImageField('Пасспорт 2', upload_to='images/users',default='',blank=True,null=True)
    driver_lisense_first = models.ImageField('Вод уд. 1', upload_to='images/users',default='',blank=True,null=True)
    driver_lisense_second = models.ImageField('Вод. уд. 2', upload_to='images/users',default='',blank=True,null=True)

    created_at = models.DateField(auto_now_add=True)
    def __str__(self):
        return f'{self.name}   {self.order_data}'


class Contacts(models.Model):
    name=models.CharField(max_length=50, verbose_name='Название организации')
    adress = models.CharField(max_length=200, verbose_name='Адрес организации')
    phone_number = models.CharField(max_length=50, verbose_name='Номер телефона')
    email = models.CharField(max_length=50, verbose_name='Электронный адрес')
    corp_number = models.CharField(max_length=50, verbose_name='Номер для корпоративный клиентов',default='',blank=True,null=True)

    def __str__(self):
        return self.name

class AboutUs(models.Model):
    image = models.ImageField('осн фотка', upload_to='images/')
    title = models.CharField(max_length=50, verbose_name='Название')
    text_first =  models.TextField('Текст о нас 1')
    text_second = models.TextField('Текст о нас 2')

    def __str__(self):
        return self.title

class SendList(models.Model):
    #information
    email = models.CharField('Email',max_length=120)

    class Meta:
        verbose_name = 'Почты для заявление'
        verbose_name_plural = 'Почты для заявление'

    def __str__(self):
        return f'{self.email}'

car_rent/main/forms.py
from django import forms
from main.models import OrderData




class OrderDataForm(forms.ModelForm):
    class Meta:
        model = OrderData
        fields = ('name', 'surname', 'phone_number', 'passport_first','passport_second',
                  'driver_lisense_first','driver_lisense_second')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя',
                'label': 'Имя',
            }),
            'surname': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фамилия и Отчество',
                'label': 'Фамилия и Отчество',
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Номер телефона',
                'id':'phonenumber',
                'label': 'Номер телефона(формат: 7 999 999 99 99)',
            }),
        }

car_rent/main/api/views.py
from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from main.models import CarModel,Car,OrderData,CarClass,CarMarka
from main.api.serializers import CarModelSerializer,CarSerializer,CarClassSerializer,\
    CarMarkaSerializer
import math
from main.api.my_paginations import PagePagination
import json

class CarListView(APIView):
    def get(self,request):
        # mobileData = json.loads(request.body.decode())
        # print(mobileData)

        data = request.GET
        class_list = request.GET['classList']
        print(json.loads(class_list))
        # class_list = request.get('classList')
        all_class_list = []
        if class_list:
            print(class_list,'here is all classlist')
            for c in json.loads(class_list):
               all_class_list.append(c["name"])

        car_model=data.get('model_id')
        car_class = data.get('checked_class')
        car_status = data.get('checked_status')
        minPrice = data.get('minPrice')
        maxPrice = data.get('maxPrice')


        filtered_cars = Car.objects.all()

        if json.loads(class_list):
            filtered_cars = filtered_cars.filter(car_class__name__in=all_class_list)



        if minPrice:
            filtered_cars=filtered_cars.filter(price__gte=minPrice).distinct()
        if maxPrice:
            filtered_cars=filtered_cars.filter(price__lte=maxPrice).distinct()
        if car_model:
                filtered_cars = filtered_cars.filter(model__id=car_model)
        if car_class:
                filtered_cars = filtered_cars.filter(car_class__name=car_class)
        if car_status and car_status=='Да':
            filtered_cars=filtered_cars.filter(taxi=True)
        if car_status and car_status=='Нет':
            filtered_cars=filtered_cars.filter(taxi=False)


        car_count = filtered_cars.count()
        car_count_for_each_page = 6
        page_count = math.ceil(car_count/car_count_for_each_page)
        page_range = range(1,page_count+1)

        page = data.get('page',1)
        if isinstance(page, str) and page.isdigit():
            page = int(page)
        cars_for_each_page = filtered_cars[(page-1)*6:page*6]
        serializered_cars = CarSerializer(cars_for_each_page,many=True)
        return Response({
            'filtered_cars': serializered_cars.data,
            'page_range': page_count,
        })

class ModelListView(APIView):
    def get(self,request):
        data = request.GET
        id = data.get('marka_id')
        models = CarModel.objects.filter(marka__id=id)
        print(models)
        serialized_models = CarModelSerializer(models,many=True)
        return Response({
                    'models': serialized_models.data,
                })

class AllCarsListView(ListAPIView):
    queryset = Car.objects.all()
    serializer_class = CarSerializer
    pagination_class = PagePagination


class OrderCreateView(APIView):

    def post(self,request):
        # data = request.POST
        form_data = json.loads(request.body.decode())
        print(form_data)
        print(form_data['userName'])
        print(form_data['userSurname'])
        order = OrderData(name=form_data['userName'],
                          surname=form_data['userSurname'],
                          phone_number=form_data['phoneNumber'],
                          order_data=form_data['orderData'])
        order.save()

        # data2 = request.body
        # print(data2)
        # request.body["orderData"]
        # print(request.body["userName"])
        # print(request.body["userSurname"])
        # print(request.body["phoneNumber"])
        # print(request.body["orderData"])
        print('its ok')

class CarClassesView(ListAPIView):
    queryset = CarClass.objects.all()
    serializer_class = CarClassSerializer

    def get(self,request):
        queryset = self.get_queryset()
        serializer = CarClassSerializer(queryset,many=True)
        return Response({
            'classes': serializer.data,
        })



class CarMarkaView(ListAPIView):
    queryset = CarMarka.objects.all()
    serializer_class = CarMarkaSerializer

    def get(self,request):
        queryset = self.get_queryset()
        serializer = CarMarkaSerializer(queryset,many=True)
        return Response({
            'allMarkas': serializer.data,
        })

car_rent/main/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,TemplateView,CreateView

from car_rent import settings
from main.models import Car,CarClass,Images,AboutUs,Contacts,CarMarka,SendList
from main.forms import OrderDataForm
from django.urls import reverse_lazy
from threading import Thread
from django.template.loader import render_to_string
import json
from django.core.mail import EmailMessage
from django.core.paginator import Paginator



# Create your views here.
class MainPageView(ListView):
    model = Car
    template_name = 'main.html'
    paginate_by = 3
    context_object_name = 'cars'

    def get_context_data(self, *args, **kwargs):
        context = super(MainPageView, self).get_context_data(**kwargs)
        context['classes'] = CarClass.objects.all()
        context['markas'] = CarMarka.objects.all()
        page = self.request.GET.get('page', 1) if self.request.GET.get('page', 1) != '' else 1
        data = self.get_queryset()
        if data:
            paginator = Paginator(data, self.paginate_by)
            results = paginator.page(page)
            index = results.number - 1
            max_index = len(paginator.page_range)
            start_index = index - 5 if index >= 5 else 0
            end_index = index + 5 if index <= max_index - 5 else max_index
            context['page_range'] = list(paginator.page_range)[start_index:end_index]
        return context

class CarDetailView(DetailView):
    model = Car
    template_name = 'detail.html'
    context_object_name = 'car'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        images = Images.objects.filter(carr__id=self.get_object().pk)
        print(images)
        context['imagess'] = images
        return context


class CreateOrderView(CreateView):
    form_class = OrderDataForm
    template_name = 'form-fill.html'
    success_url='/success'

    # def get_success_url(self):
    #     return render(self.request,'success.html')

    #

    def form_valid(self,form):
        order = form.save(commit=False)
        order.order_data = self.request.POST.get('all-data')
        order.save()
        return super().form_valid(form)


# def send_email():
#     template_name = 'send-email.html'
#     context = {
#         'data': 'data'
#     }
#     msg = render_to_string(template_name, context)
#     subject = 'Новое заявление'
#     user_emails = SendList.objects.all().values_list('email', flat=True)
#     message = EmailMessage(subject=subject, body=msg, from_email=settings.EMAIL_HOST_USER, to=user_emails)
#     message.content_subtype = 'html'
#     message.send()


class OrderSuccessView(TemplateView):
    # Thread(target=send_email).start()
    template_name = 'success.html'

class AboutUsView(TemplateView):
    template_name = 'about-us.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        about = AboutUs.objects.first()
        context['about'] = about
        return context

class ContactPageView(TemplateView):
    template_name = 'contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        contacts = Contacts.objects.first()
        context['contacts'] = contacts
        return context

car_rent/main/templates/includes/footer.html
<footer>
    <div class="footer-background">
        <div class="my_container">
            <div class="row text-center" style="padding-right: 40.5px;padding-left: 40.5px">
                <div class="col-xl-4 col-12 footer-parts" id="footer-parts">
                    <div class="d-flex class-footer-img">
                        <div class="footer-img">
                            <img class="nd_options_float_left" alt="" src="http://www.nicdarkthemes.com/themes/restaurant/wp/demo/restaurant/wp-content/uploads/sites/2/2019/01/social-1.png" width="20">
                        </div>
                        <div class="footer-img">
                            <img class="nd_options_float_left" alt="" src="http://www.nicdarkthemes.com/themes/restaurant/wp/demo/restaurant/wp-content/uploads/sites/2/2019/01/social-3.png" width="20">
                        </div>
                        <div class="footer-img">
                            <img class="nd_options_float_left" alt="" src="http://www.nicdarkthemes.com/themes/restaurant/wp/demo/restaurant/wp-content/uploads/sites/2/2019/01/social-2.png" width="20">
                        </div>
                        <div class="footer-img">
                            <img class="nd_options_float_left" alt="" src="http://www.nicdarkthemes.com/themes/restaurant/wp/demo/restaurant/wp-content/uploads/sites/2/2019/01/social-4.png" width="20">
                        </div>
                        <div class="footer-img">
                            <img class="nd_options_float_left" alt="" src="http://www.nicdarkthemes.com/themes/restaurant/wp/demo/restaurant/wp-content/uploads/sites/2/2019/01/social-5.png" width="20">
                        </div>
                    </div>
                    <div>
                        <p style="font-size:12px;margin-top:10px">STAY TUNED</p>
                    </div>
                    <div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu libero elit.</p>
                    </div>
                </div>
                <div class="col-12 col-xl-4 footer-parts">
                    <div>
                        <img alt="" style="width:120px;" class=" nd_options_margin_0 nd_options_padding_0 " src="">
                    </div>
                    <div style="height: 20px;"></div>
                    <div>
                        <p style="margin: 0px">info@restaurant.com</p>
                        <p>+12 476 357 384</p>
                    </div>
                </div>
                <div class="col-12 col-xl-4 footer-list footer-parts">
                    <p class="py-2">Əsas səhifə</p>
                    <p class="py-2">Haqqımızda</p>
                    <p class="py-2">Kontaktlar</p>
                    <p class="py-2">Elan yerləşdir</p>
                    
                </div>
            </div>
        </div>
    </div>
    
</footer>

car_rent/main/templates/includes/navbar.html
    <section style="height: 500px;">
      
      
            <div class="inhamburger-parent" style="position: relative;">
                <div class="inhamburger" style="background-color: rgb(45, 45, 45);">
                    <ul class="hamburger-ul pl-4">
                        <div class="hamburger-x mt-3">
                            <img
                                src="http://www.nicdarkthemes.com/themes/restaurant/wp/demo/restaurant/wp-content/plugins/nd-shortcodes/addons/customizer/header/header-2/img/icon-close-white.svg">
                        </div>
                        <li class="hamburger-ul-li mt-4"><a href='/'>Главная</a>
                            
                        </li>
                        <li class="hamburger-ul-li mt-3"><a href="{% url 'main:about-us' %}">О нас</a>
                            
                        </li>
                        <li class="hamburger-ul-li mt-3"><a href="{% url 'main:contacts' %}">Контакты</a>
                            
                        </li>
                        
                    </ul>
                </div>
            </div>
            <div
                class="container-fluid under-the-header nd_options_section nd_options_background_size_cover nd_options_background_position_center_bottom">
                <div class="row div-under-header">
                    <div class="col-xl-2 d-none d-lg-flex logo-ristorante">
                        <span><img alt="" style="width:120px;" class=" nd_options_margin_0 nd_options_padding_0 "
                                src="http://www.nicdarkthemes.com/themes/restaurant/wp/demo/restaurant/wp-content/uploads/sites/2/2019/01/logo.png"></span>
                    </div>
                    <div class="hamburger d-xl-none" style="float: right;">
                        <div class="line"></div>
                        <div class="line"></div>
                        <div class="line"></div>
                        <div class="line"></div>
                    </div>
                    <div class="col-xl-8 d-none d-lg-flex justify-content-center">
                        <div class="nav-div">
                            <ul class="header-ul ">
                                <li class="main-li menu-home"><a href='/'>Главная</a>
                                    
                                </li>
                                <li class="main-li menu-about"><a href="{% url 'main:about-us' %}" >О нас</a>
                                    
                                </li>
                          
                                <li class="main-li main-contact book-a-table"><a href="{% url 'main:contacts' %}">Контакты</a>
                                    
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-2 d-none d-lg-flex">
                        <span class="message-png container">
                            <img class="nd_options_float_left" alt="" width="25"
                                src="http://www.nicdarkthemes.com/themes/restaurant/wp/demo/restaurant/wp-content/uploads/sites/2/2019/01/ico-07.png">
                        </span>
                    </div>
                    <div>
                        <div class="empty-for-height"></div>
                        <h1 class="h1-book-a-table">Tach-Rent</h1>
                    </div>
                </div>
    
            </div>
  
    </section>