car_rent/car_rent/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('api/v1.0/cars/',include('main.api.urls',namespace='api_cars')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rent/main/api/urls.py
from django.urls import path
from main.api.views import ModelListView,CarListView,AllCarsListView,OrderCreateView, \
CarClassesView,CarMarkaView

app_name = 'api_cars'

urlpatterns = [
    path('cars/',CarListView.as_view(),name='cars'),
    path('models/',ModelListView.as_view(),name= 'models'),
    path('all/',AllCarsListView.as_view(),name='all'),
    path('orders/',OrderCreateView.as_view(),name='orders'),
    path('classes/',CarClassesView.as_view(),name='classes'),
    path('markas/',CarMarkaView.as_view(),name='markas')

]

car_rent/main/urls.py
from django.urls import path
from main.views import MainPageView,CarDetailView,CreateOrderView,OrderSuccessView,AboutUsView,ContactPageView


app_name = 'main'


urlpatterns = [
    path('',MainPageView.as_view(),name='home'),
    path('car-detail/<int:pk>/',CarDetailView.as_view(),name='car-detail'),
    path('create-order/',CreateOrderView.as_view(),name='create-order'),
    path('success/',OrderSuccessView.as_view(),name='success'),
    path('about/',AboutUsView.as_view(),name='about-us'),
    path('contacts/',ContactPageView.as_view(),name='contacts')

]

car_rent/main/models.py
from django.db import models



class CarMarka(models.Model):
    marka = models.CharField(max_length=50, verbose_name='Marka')

    def __str__(self):
        return self.marka

class CarModel(models.Model):
    marka = models.ForeignKey(CarMarka, on_delete=models.CASCADE, verbose_name='Marka',related_name='models')
    model = models.CharField(max_length=50, verbose_name='Model')

    def __str__(self):
        return self.model

class CarYear(models.Model):
    # model = models.ForeignKey(CarModel, on_delete=models.CASCADE, verbose_name='Model',related_name='years')
    year = models.PositiveIntegerField(verbose_name='Год выпуска')

    def __str__(self):
        return str(self.year)

class Transmission(models.Model):
    name = models.CharField(max_length=50, verbose_name='Коробка')

    def __str__(self):
        return str(self.name)

class Fuel(models.Model):
    name = models.CharField(max_length=50, verbose_name='Топливо')

    def __str__(self):
        return str(self.name)

class Type(models.Model):
    name = models.CharField(max_length=50, verbose_name='Кузов')

    def __str__(self):
        return str(self.name)

class CarClass(models.Model):
    name = models.CharField(max_length=50, verbose_name='Класс')

    def __str__(self):
        return str(self.name)

# Create your models here.
class Car(models.Model):
    marka = models.ForeignKey(CarMarka, on_delete=models.CASCADE, null=True, verbose_name='Марка',related_name='cars')
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE, null=True, verbose_name='Модель',related_name='cars')
    car_year = models.ForeignKey(CarYear, on_delete=models.CASCADE, null=True, verbose_name='Год выпуска',related_name='cars')
    transmission = models.ForeignKey(Transmission,on_delete=models.CASCADE, null=True, verbose_name='Коробка передач',related_name='cars')
    main_image = models.ImageField('Main image', upload_to='images/main')
    price = models.PositiveIntegerField(verbose_name='Стоимость')
    fuel = models.ForeignKey(Fuel, on_delete=models.CASCADE, null=True, verbose_name='Топливо', related_name='cars')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, null=True, verbose_name='Кузов', related_name='cars')
    car_class = models.ForeignKey(CarClass, on_delete=models.CASCADE, null=True, verbose_name='Класс авто', related_name='cars')
    seats = models.CharField(max_length=50, verbose_name='Количество сиденье')
    comment = models.TextField('Oписание')

    is_published = models.BooleanField(default=False, verbose_name='Опубликован')
    taxi = models.BooleanField(default=False, verbose_name='Такси')

    def get_image(self):
        return self.main_image.url

    def get_car(self):
        return f'{self.marka.marka} {self.model.model} {self.car_year.year}'




class Images(models.Model):
    carr = models.ForeignKey(Car,on_delete=models.CASCADE, verbose_name='Car',related_name='images')
    images = models.ImageField('Допольнительные фотографии', upload_to='images/allImg')

    def __str__(self):
        return f'{self.images}'


class OrderData(models.Model):
    name=models.CharField(max_length=50, verbose_name='Имя')
    surname=models.CharField(max_length=50, verbose_name='Фамилия и Отчество')
    phone_number=models.CharField(max_length=50, verbose_name='Номер телефона')
    order_data=models.CharField(max_length=250, verbose_name='Заказ')
    passport_first = models.ImageField('Пасспорт 1', upload_to='images/users',default='',blank=True,null=True)
    passport_second = models.ImageField('Пасспорт 2', upload_to='images/users',default='',blank=True,null=True)
    driver_lisense_first = models.ImageField('Вод уд. 1', upload_to='images/users',default='',blank=True,null=True)
    driver_lisense_second = models.ImageField('Вод. уд. 2', upload_to='images/users',default='',blank=True,null=True)

    created_at = models.DateField(auto_now_add=True)
    def __str__(self):
        return f'{self.name}   {self.order_data}'


class Contacts(models.Model):
    name=models.CharField(max_length=50, verbose_name='Название организации')
    adress = models.CharField(max_length=200, verbose_name='Адрес организации')
    phone_number = models.CharField(max_length=50, verbose_name='Номер телефона')
    email = models.CharField(max_length=50, verbose_name='Электронный адрес')
    corp_number = models.CharField(max_length=50, verbose_name='Номер для корпоративный клиентов',default='',blank=True,null=True)

    def __str__(self):
        return self.name

class AboutUs(models.Model):
    image = models.ImageField('осн фотка', upload_to='images/')
    title = models.CharField(max_length=50, verbose_name='Название')
    text_first =  models.TextField('Текст о нас 1')
    text_second = models.TextField('Текст о нас 2')

    def __str__(self):
        return self.title

class SendList(models.Model):
    #information
    email = models.CharField('Email',max_length=120)

    class Meta:
        verbose_name = 'Почты для заявление'
        verbose_name_plural = 'Почты для заявление'

    def __str__(self):
        return f'{self.email}'

car_rent/main/forms.py
from django import forms
from main.models import OrderData




class OrderDataForm(forms.ModelForm):
    class Meta:
        model = OrderData
        fields = ('name', 'surname', 'phone_number', 'passport_first','passport_second',
                  'driver_lisense_first','driver_lisense_second')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя',
                'label': 'Имя',
            }),
            'surname': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фамилия и Отчество',
                'label': 'Фамилия и Отчество',
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Номер телефона',
                'id':'phonenumber',
                'label': 'Номер телефона(формат: 7 999 999 99 99)',
            }),
        }

car_rent/main/api/views.py
from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from main.models import CarModel,Car,OrderData,CarClass,CarMarka
from main.api.serializers import CarModelSerializer,CarSerializer,CarClassSerializer,\
    CarMarkaSerializer
import math
from main.api.my_paginations import PagePagination
import json

class CarListView(APIView):
    def get(self,request):
        # mobileData = json.loads(request.body.decode())
        # print(mobileData)

        data = request.GET
        class_list = request.GET['classList']
        print(json.loads(class_list))
        # class_list = request.get('classList')
        all_class_list = []
        if class_list:
            print(class_list,'here is all classlist')
            for c in json.loads(class_list):
               all_class_list.append(c["name"])

        car_model=data.get('model_id')
        car_class = data.get('checked_class')
        car_status = data.get('checked_status')
        minPrice = data.get('minPrice')
        maxPrice = data.get('maxPrice')


        filtered_cars = Car.objects.all()

        if json.loads(class_list):
            filtered_cars = filtered_cars.filter(car_class__name__in=all_class_list)



        if minPrice:
            filtered_cars=filtered_cars.filter(price__gte=minPrice).distinct()
        if maxPrice:
            filtered_cars=filtered_cars.filter(price__lte=maxPrice).distinct()
        if car_model:
                filtered_cars = filtered_cars.filter(model__id=car_model)
        if car_class:
                filtered_cars = filtered_cars.filter(car_class__name=car_class)
        if car_status and car_status=='Да':
            filtered_cars=filtered_cars.filter(taxi=True)
        if car_status and car_status=='Нет':
            filtered_cars=filtered_cars.filter(taxi=False)


        car_count = filtered_cars.count()
        car_count_for_each_page = 6
        page_count = math.ceil(car_count/car_count_for_each_page)
        page_range = range(1,page_count+1)

        page = data.get('page',1)
        if isinstance(page, str) and page.isdigit():
            page = int(page)
        cars_for_each_page = filtered_cars[(page-1)*6:page*6]
        serializered_cars = CarSerializer(cars_for_each_page,many=True)
        return Response({
            'filtered_cars': serializered_cars.data,
            'page_range': page_count,
        })

class ModelListView(APIView):
    def get(self,request):
        data = request.GET
        id = data.get('marka_id')
        models = CarModel.objects.filter(marka__id=id)
        print(models)
        serialized_models = CarModelSerializer(models,many=True)
        return Response({
                    'models': serialized_models.data,
                })

class AllCarsListView(ListAPIView):
    queryset = Car.objects.all()
    serializer_class = CarSerializer
    pagination_class = PagePagination


class OrderCreateView(APIView):

    def post(self,request):
        # data = request.POST
        form_data = json.loads(request.body.decode())
        print(form_data)
        print(form_data['userName'])
        print(form_data['userSurname'])
        order = OrderData(name=form_data['userName'],
                          surname=form_data['userSurname'],
                          phone_number=form_data['phoneNumber'],
                          order_data=form_data['orderData'])
        order.save()

        # data2 = request.body
        # print(data2)
        # request.body["orderData"]
        # print(request.body["userName"])
        # print(request.body["userSurname"])
        # print(request.body["phoneNumber"])
        # print(request.body["orderData"])
        print('its ok')

class CarClassesView(ListAPIView):
    queryset = CarClass.objects.all()
    serializer_class = CarClassSerializer

    def get(self,request):
        queryset = self.get_queryset()
        serializer = CarClassSerializer(queryset,many=True)
        return Response({
            'classes': serializer.data,
        })



class CarMarkaView(ListAPIView):
    queryset = CarMarka.objects.all()
    serializer_class = CarMarkaSerializer

    def get(self,request):
        queryset = self.get_queryset()
        serializer = CarMarkaSerializer(queryset,many=True)
        return Response({
            'allMarkas': serializer.data,
        })

car_rent/main/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,TemplateView,CreateView

from car_rent import settings
from main.models import Car,CarClass,Images,AboutUs,Contacts,CarMarka,SendList
from main.forms import OrderDataForm
from django.urls import reverse_lazy
from threading import Thread
from django.template.loader import render_to_string
import json
from django.core.mail import EmailMessage
from django.core.paginator import Paginator



# Create your views here.
class MainPageView(ListView):
    model = Car
    template_name = 'main.html'
    paginate_by = 3
    context_object_name = 'cars'

    def get_context_data(self, *args, **kwargs):
        context = super(MainPageView, self).get_context_data(**kwargs)
        context['classes'] = CarClass.objects.all()
        context['markas'] = CarMarka.objects.all()
        page = self.request.GET.get('page', 1) if self.request.GET.get('page', 1) != '' else 1
        data = self.get_queryset()
        if data:
            paginator = Paginator(data, self.paginate_by)
            results = paginator.page(page)
            index = results.number - 1
            max_index = len(paginator.page_range)
            start_index = index - 5 if index >= 5 else 0
            end_index = index + 5 if index <= max_index - 5 else max_index
            context['page_range'] = list(paginator.page_range)[start_index:end_index]
        return context

class CarDetailView(DetailView):
    model = Car
    template_name = 'detail.html'
    context_object_name = 'car'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        images = Images.objects.filter(carr__id=self.get_object().pk)
        print(images)
        context['imagess'] = images
        return context


class CreateOrderView(CreateView):
    form_class = OrderDataForm
    template_name = 'form-fill.html'
    success_url='/success'

    # def get_success_url(self):
    #     return render(self.request,'success.html')

    #

    def form_valid(self,form):
        order = form.save(commit=False)
        order.order_data = self.request.POST.get('all-data')
        order.save()
        return super().form_valid(form)


# def send_email():
#     template_name = 'send-email.html'
#     context = {
#         'data': 'data'
#     }
#     msg = render_to_string(template_name, context)
#     subject = 'Новое заявление'
#     user_emails = SendList.objects.all().values_list('email', flat=True)
#     message = EmailMessage(subject=subject, body=msg, from_email=settings.EMAIL_HOST_USER, to=user_emails)
#     message.content_subtype = 'html'
#     message.send()


class OrderSuccessView(TemplateView):
    # Thread(target=send_email).start()
    template_name = 'success.html'

class AboutUsView(TemplateView):
    template_name = 'about-us.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        about = AboutUs.objects.first()
        context['about'] = about
        return context

class ContactPageView(TemplateView):
    template_name = 'contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        contacts = Contacts.objects.first()
        context['contacts'] = contacts
        return context

car_rent/main/templates/about-us.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center py-3" >{{about.title}}</h1>
        </div>
        <div class="col-12 py-3">
            {{about.text_first}}
        </div>
        <div class="col-12">
            <img style="width: 100%; height: 100%;" src="{{about.image.url}}" alt="">
            
        </div>
        <div class="col-12 py-3">
            {{about.text_second}}
        </div>
    </div>
</div>
{% endblock %}

car_rent/main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Home {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    <link rel="stylesheet" href="{% static 'css/pignose.calendar.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/subscribe.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block css %}
    {% endblock %}
</head>

<body>

    {% include 'includes/navbar.html' %}

    {% block content %}





    {% endblock %}
{% include 'includes/footer.html' %}
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/moment-with-locales.js' %}"></script>
        <script src="{% static 'js/filters.js' %}"></script>

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <!-- <script src="{% static 'js/main.js' %}"></script> -->

        <script src="//cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.4/hammer.min.js"></script>
    <script>
        document.querySelector('.hamburger').addEventListener('click', function () {
            document.querySelector('.inhamburger').classList.toggle('show');
        })
        document.querySelector('.hamburger-x').addEventListener('click', function () {
            document.querySelector('.inhamburger').classList.toggle('show');
        })
    </script>
    <script src="{% static 'js/detail.js' %}"></script>
    <script src="{% static 'js/pignose.calendar.js' %}"></script>
    <script src="{% static 'js/gallery.js' %}"></script>
    {% block js %}
    {% endblock %}
</body>

</html>

car_rent/main/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


{% endblock %}
{% block content %}


<div class="container p-4 ">
    <div class="row justify-content-center">
        <div class=" col-xl-3 col-12">
            <h4>Фильтры</h4>
            <div class="row ">

                <div class="col-xl-12  col-lg-5 col-12">
                    <div class="row">
                        <div class="col-12 border p-2 my-1">
                            <div class="py-2">
                                <h6 class="bolder-words">По цене : </h6>
                            </div>
                            <div class="input-group input-group-sm mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text min-span" id="inputGroup-sizing-sm">min</span>
                                </div>
                                <input type="text" class="form-control min-price" aria-label="Small"
                                    aria-describedby="inputGroup-sizing-sm">
                            </div>
                            <div class="input-group input-group-sm mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text max-span " id="inputGroup-sizing-sm">max</span>
                                </div>
                                <input type="text" class="form-control max-price" aria-label="Small"
                                    aria-describedby="inputGroup-sizing-sm">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-12 mr-lg-2 mb-lg-2 col-lg-5 col-12">
                    <div class="row">
                        <div class="col-12  p-2 my-1 d-flex flex-column">
                            <h6 class="bolder-words">Выберите марку :</h6>
                            
                            <select class="border-0 bg-primary text-white p-2 for-selection" name="cars" id="cars">
                                <option class="text-white bg-primary marka" >.... 
                                </option>
                                {% for marka in markas %}
                                <option class="text-white bg-primary marka" value="{{marka.pk}}">{{marka.marka}}
                                </option>
                                {% endfor %}

                            </select>

                        </div>
                        <div class="col-12  p-2 my-1 d-flex flex-column">
                            <h6 class="bolder-words">Выберите модель :</h6>
                            <select class="border-0 bg-primary text-white p-2 model-select" name="cars" id="cars">

                                <option class="text-white bg-primary marka">Сначало выберите марку</option>
                            </select>

                        </div>


                    </div>
                </div>
                <div class="col-xl-12 col-lg-5 col-12">
                    <div class="row">
                        <div class="col-12 border p-2 my-1">
                            <div class="py-2">
                                <h6 class="bolder-words">Класс автомобиля </h6>
                            </div>
                            <div class="">
                                {% for class in classes %}
                                <div class="ally" id="amenities-hotel">

                                    <label class="containerr"><span class="pl-3 choose-types">
                                            {{class.name}}
                                        </span>
                                        <input type="radio" class="checked-inputs feature" name="radio">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-12 col-lg-5 col-12">
                    <div class="row">
                        <div class="col-12 border p-2 my-1">
                            <div class="py-2">
                                <h6 class="bolder-words">Аренда под такси </h6>
                            </div>
                            <div class="">
                                <div class="ally" id="amenities-hotel">

                                    <label class="containerr"><span class="pl-3 choose-types">Да
                                        </span>
                                        <input type="radio" class="checked-inputs types" name="radios">
                                        <span class="checkmark"></span>
                                    </label>
                                   
                                </div>
                                <div class="ally" id="amenities-hotel">

                                   
                                    <label class="containerr"><span class="pl-3 choose-types">Нет
                                        </span>
                                        <input type="radio" class="checked-inputs types" name="radios">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
        <div class="col-xl-9 col-12 main-col">
            <div class="row">
                <div class="col-12">
                    <h4 class="baku-125" style="font-weight: bold;">Арендуйте у нас : </h4>
                </div>
            </div>
            <div class="removed-data">
            {% for car in cars %}
            
                <div class="row main-div">
                    <div class="col-12 ">
                        <div class="card mb-3 p-3"
                            style="max-width: 100%; height: 90%;border-color: #5bbaff;box-shadow: 0 0 10px #5bbaff;background-color: #ebf3ff;">
                            <div class="row no-gutters">
                                <div class="col-md-4 col-sm-6 col-lg-3 col-12">
                                    <img class="content-image card-img" src="{{car.main_image.url}}">
                                </div>
                                <div class="col-md-4 col-sm-6 col-lg-6 col-12">
                                    <div class="card-body">
                                        <h6 class="card-title text-primary mb-1" style="font-weight: bold;">
                                            {{car.marka}} {{car.model}} ({{car.fuel}})</h6>
                                        <div class="d-flex align-items-center mb-3 ">
                                        </div>
                                        <p class="card-text" style="font-size: 12px;line-height: 18px;">
                                            {{car.car_year}} model car</p>
                                        <p class="card-text"><small class="text-muted">Best car</small>
                                        </p>
                                        <span class="d-sm-block d-md-none" style="font-size: 16px;">Price
                                            for night
                                            {{car.price}} руб.</span>
                                    </div>
                                </div>
                                <div class="col-md-4 col-sm-6 col-lg-3 d-none d-md-block col-12">
                                    <div class="row flex-column justify-content-between h-100 ">
                                        
                                        <div class=" d-flex flex-column justify-content-end h-100 px-2">
                                      
                                            <span class="text-right mb-2" style="font-size: 16px;">Price for night
                                                {{car.price}} руб.</span>
                                                <a href="{% url 'main:car-detail' car.id %}" type="button"
                                                class="btn btn-danger slugs-anchor"
                                                style="font-size:14px; color: white;">Арендовать</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 p-sm-3  pb-4 pl-4 d-block d-sm-none ">
                                    <div class="row  ">
                                        <a href="" type="button" class="btn btn-danger slugs-anchor w-25"
                                            style="font-size:14px; color: white;">Арендовать</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            
            {% endfor %}
        </div>
        <div class="row mt-5 old-pagi">
            <div class="col text-center">
                <div class="block-27 d-flex justify-content-center align-items-center">
                    {% if page_obj.has_previous %}
                    <a class="prev-icon" style="color: #b0ddf2;"
                        href="?page={{ page_obj.previous_page_number }}{% if sortBy %}&sortBy={{ sortBy }}{% endif %}">
                        <i class='fas fa-angle-left previous-icon mr-2' alt="arrow" style='font-size:24px'></i>
                    </a>
                    {% endif %}
                    {% if page_range|length > 1 %}
                    <div class="page-numbers">
                        {% for page_number in page_range %}
                        {% if page_number == page_obj.number %}
                        <a class="active mr-2">
                            <span>{{ page_number }}</span>
                        </a>
                        {% else %}
                        <a class="page mr-2 deactive-page-numbers mb-2"
                            style="text-decoration: none;color: rgb(145, 145, 255);"
                            href="?page={{ page_number }}{% if sortBy %}&sortBy={{ sortBy }}{% endif %}">
                            <span class="number-span">{{ page_number }}</span>
                        </a>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <a class="next-page ml-2" style="color: #b0ddf2;"
                        href="?page={{ page_obj.next_page_number }}{% if sortBy %}&sortBy={{ sortBy }}{% endif %}">
                        <i class=' fas fa-angle-right' style='font-size:24px' alt="arrow" class="next-icon"></i>

                    </a>
                    {% endif %}

                </div>
            </div>
        </div>
        <div class="row js-pagination d-flex justify-content-center align-items-center">

        </div>
        </div>
    </div>
</div>




{% endblock %}



{% block js %}

{% endblock %}

car_rent/main/templates/send-email.html
{% load static %}
{% block content %}
    <div>
        <p>У вас новое заявление проверьте админку.</p>
    </div>
{% endblock %}